Fix QUOTEDSTRING pattern regex
Fix QUOTEDSTRING pattern regex. The actual regex is causing a
preg_match_all error: "preg_match_all(): Compilation failed: missing ) at
offset 83" because of missing "\\" in the regex. This commit also
creates a test to grant that the regex is working.